version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: bas-transport-service
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS1:/dev/ttyS1"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      
